In [136]:
import torch as T
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import pandas as pd
import os
from datetime import datetime

In [59]:
X = T.rand(size=(12, 1000, 1))
output, hidden_state = nn.GRU(X.shape[0], 256)(X.permute(1, 2, 0).contiguous())

In [58]:
nn.Parameter((T.zeros(size=(1, 1)))

torch.Size([1000, 1, 256])

In [20]:
x = T.rand((12, 12))
x = T.tensor([i if i >= .12 else 0 for i in T.flatten(x)]).reshape(x.shape)
x.shape

torch.Size([12, 12])

In [23]:
x.sum(-1)

tensor([5.0771, 4.5079, 4.5604, 5.0516, 6.0807, 5.7380, 7.2921, 6.9615, 5.3979,
        5.8541, 5.8715, 6.9066])

In [37]:
tuple([5,2])[:2]

(5, 2)

In [44]:
PATH = '/Users/jakemehlman/Desktop/Minute_Data_v1/'
DF = pd.read_csv(PATH + 'AAPL.USUSD_Candlestick_1_M_ASK_02.11.2017-01.01.2020.csv')
DF2 = pd.read_csv(PATH + 'AMZN.USUSD_Candlestick_1_M_ASK_02.11.2017-01.01.2020.csv')

In [71]:
DF.head(50)

Local time   High     Low  Close       Volume
0   02.11.2017 09:30:00.000 GMT-0400  56.02  55.800  55.85  276127.9941
1   02.11.2017 09:31:00.000 GMT-0400  55.93  55.820  55.93  499300.9865
2   02.11.2017 09:32:00.000 GMT-0400  55.96  55.870  55.90  420192.0033
3   02.11.2017 09:33:00.000 GMT-0400  56.02  55.900  55.95  491483.0029
4   02.11.2017 09:34:00.000 GMT-0400  56.01  55.950  56.00  355295.9859
5   02.11.2017 09:35:00.000 GMT-0400  56.00  55.860  55.89  312660.9921
6   02.11.2017 09:36:00.000 GMT-0400  55.94  55.870  55.92  265807.0028
7   02.11.2017 09:37:00.000 GMT-0400  55.97  55.920  55.94  238959.9979
8   02.11.2017 09:38:00.000 GMT-0400  55.97  55.910  55.94  202360.0042
9   02.11.2017 09:39:00.000 GMT-0400  55.98  55.910  55.98  391635.0007
10  02.11.2017 09:40:00.000 GMT-0400  55.98  55.920  55.96  286590.0099
11  02.11.2017 09:41:00.000 GMT-0400  56.12  55.960  56.12  268564.9991
12  02.11.2017 09:42:00.000 GMT-0400  56.20  56.120  56.13  311315.0001
13  02.11.2017 09:43:00.000 GMT-0400  56.15  56.090  56.11  245324.0007
14  02.11.2017 09:44:00.000 GMT-0400  56.13  56.110  56.13  182435.0059
15  02.11.2017 09:45:00.000 GMT-0400  56.16  56.070  56.10  292109.9961
16  02.11.2017 09:46:00.000 GMT-0400  56.11  56.080  56.09  178900.0034
17  02.11.2017 09:47:00.000 GMT-0400  56.12  56.090  56.10  187987.9981
18  02.11.2017 09:48:00.000 GMT-0400  56.11  56.010  56.02  278456.9860
19  02.11.2017 09:49:00.000 GMT-0400  56.02  55.990  56.01  143260.0021
20  02.11.2017 09:50:00.000 GMT-0400  56.05  56.010  56.04  113229.9975
21  02.11.2017 09:51:00.000 GMT-0400  56.04  55.950  56.01  245230.0042
22  02.11.2017 09:52:00.000 GMT-0400  56.04  56.010  56.03  169964.9990
23  02.11.2017 09:53:00.000 GMT-0400  56.02  56.000  56.00   18789.9992
24  02.11.2017 09:54:00.000 GMT-0400  56.01  55.970  55.98  165879.9946
25  02.11.2017 09:55:00.000 GMT-0400  55.99  55.920  55.92  131355.0025
26  02.11.2017 09:56:00.000 GMT-0400  55.93  55.890  55.91  146439.9993
27  02.11.2017 09:57:00.000 GMT-0400  55.96  55.910  55.96  173840.0012
28  02.11.2017 09:58:00.000 GMT-0400  55.97  55.940  55.95  146884.9927
29  02.11.2017 09:59:00.000 GMT-0400  55.96  55.900  55.91  128989.9945
30  02.11.2017 10:00:00.000 GMT-0400  55.91  55.880  55.88  200554.9967
31  02.11.2017 10:01:00.000 GMT-0400  55.87  55.810  55.81  128058.9998
32  02.11.2017 10:02:00.000 GMT-0400  55.85  55.820  55.85   98595.0008
33  02.11.2017 10:03:00.000 GMT-0400  55.87  55.750  55.79  210899.9938
34  02.11.2017 10:04:00.000 GMT-0400  55.81  55.760  55.76  301304.9960
35  02.11.2017 10:05:00.000 GMT-0400  55.77  55.620  55.62  248073.9951
36  02.11.2017 10:06:00.000 GMT-0400  55.64  55.570  55.59  207870.0066
37  02.11.2017 10:07:00.000 GMT-0400  55.59  55.550  55.59  125000.0000
38  02.11.2017 10:08:00.000 GMT-0400  55.59  55.520  55.54  254460.0070
39  02.11.2017 10:09:00.000 GMT-0400  55.53  55.480  55.53  112609.9974
40  02.11.2017 10:10:00.000 GMT-0400  55.55  55.490  55.54  182543.9930
41  02.11.2017 10:11:00.000 GMT-0400  55.56  55.520  55.53  100740.0006
42  02.11.2017 10:12:00.000 GMT-0400  55.53  55.470  55.48   76310.0013
43  02.11.2017 10:13:00.000 GMT-0400  55.48  55.360  55.37  233235.0016
44  02.11.2017 10:14:00.000 GMT-0400  55.41  55.370  55.41   61090.0000
45  02.11.2017 10:15:00.000 GMT-0400  55.49  55.400  55.49  225830.0036
46  02.11.2017 10:16:00.000 GMT-0400  55.54  55.493  55.53  412526.9949
47  02.11.2017 10:17:00.000 GMT-0400  55.55  55.510  55.51  115965.0013
48  02.11.2017 10:18:00.000 GMT-0400  55.53  55.500  55.50  224947.0055
49  02.11.2017 10:19:00.000 GMT-0400  55.58  55.500  55.58  123429.9988

In [180]:
PATH = '/Users/jakemehlman/Desktop/Minute_Data_v1/'
def make_DF(PATH):
    DFNEW = pd.DataFrame()
    for filename in os.listdir(PATH):
        DF = pd.read_csv(PATH + filename)
        DF = DF[['Local time', 'High', 'Low', 'Close', 'Volume']]
        try:
            DFNEW = DFNEW.merge(DF, left_on='Local time', right_on='Local time')
        except:
            DFNEW = DF
    DFNEW = DFNEW.replace(0, 1)
    return DFNEW

def make_global_tensor_no_time(df):
    arr = np.array(df)[:, 1:] # (time, features)
    Arr = np.array(arr[1:, :] / arr[:-1, :]).astype(float)
    X = T.ones((Arr.shape[-1] // 4, 4, Arr.shape[0]))
    for i in range(arr.shape[-1]):
        j = i // 4
        k = i % 4
        X[j, k, :] = T.tensor(Arr[:, i])
    return X


def make_global_temporal_tensor(df):
    arr = np.array(df)[:, 0]
    M = T.zeros((arr.shape[0], 36))
    for i in range(1, arr.shape[0]):
        base = arr[i]

        half_hour = T.tensor(2 * (int(base[11:13]) - 9) + (int(base[14:16]) >= 30))
        day = T.tensor(datetime.strptime(base[:10].replace('.', ' '), '%d %m %Y').isoweekday())
        week = T.tensor(abs(int(base[:2]) - 4) // 7)
        month = T.tensor(int(base[3:5]))

        half_hour = F.one_hot(half_hour-1, 15)
        day = F.one_hot(day-1, 5)
        week = F.one_hot(week, 4)
        month = F.one_hot(month-1, 12)
        M[i, :] = T.cat((half_hour, day, week, month))
    return M[1:, :]

tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.])

In [148]:
X.shape
datetime.strptime(arr[0][:10].replace('.', ' '), '%d %m %Y').isoweekday()

4

In [ ]:
def one_hot_encoding(string):
    ###
    # string: string - original timestamp
    
    # output: array - one hot encoded time - (half hour of trading day, day of week, week of month, month of year) dim-15+5+4+12=36
    
    return output

In [109]:
arr[:5, 4]
#DFNEW.head(10)

array([137749.9998, 98353.9969, 126066.9976, 127960.9948, 27499.9999],
      dtype=object)